### ISSUE TITLE
Please, get email address vía GET

### ISSUE THREAD

**Issue by mautematico** [7THStage/idigdoge#1]
I don't know jade, but i think it is possible to obtain GET parameters, like:

www.idigdoge.com/?email=doge@creepypastas.com
or
www.idigdoge.com/?digfor=doge@creepypastas.com

So people can easily share a URL whit friends and digdoge togetter.
Also webmasters will be able to put an iframe in their websites and ask visitors to digdoge for website.

Plus:
get Intensity via GET, so webmasters can do:
www.idigdoge.com/?digefor=doge@creepypastas.com&intensity=2

**Comment by 7THStage** [comment]
It actually isn't possible to obtain GET parameters directly from a Jade template. They can easily be passed in the render call though. Just FYI. :)

Now, I'm going to explain why I'm answering this the way I am: I REALLY don't want I Dig Doge used by webmasters, at least not in a frame. It's not what it was made for, and it's not optimized for it. It makes a lot of server calls and does a lot of processing so that people who visit the site should get a balance within their first minute, even on old computers. It was built as an introduction to crypto currencies, and hopefully I'll get the time to move it more towards that with a design and content update. However, I am working on an alternative that is made as an advertising alternative. It's not ready for primetime yet though.

With that in mind, I already planned to allow people to share the site and get a balance bonus. It may offer people the option to dig for whoever recommend them, but it will dig for the new visitor by default.

I will definitely not allow setting of the intensity by URL. I plan to re-implement the previous "Auto" functionality as the default, which tries to find the optimum value. The optimum intensity is actually the number of cores on the visitor's CPU.

Of course, you're welcome to fork the project and change it however you like. If you allow your change to be optional with a setting in the config file, you can even submit a pull request. But as for IDigDoge.com, it will work as I just described. Also, sorry if this message sounds harsh; that's not my intent. I just wanted to explain my decision beyond a big NO, and provide a bit of a roadmap.
