### ISSUE TITLE
Verification of Valid Address

### ISSUE THREAD

**Issue by leadcoin** [7THStage/idigdoge#19]
Real quick question, figured it'd be appropriate for an issue since it involves the difference between a version change.  

When verifying a valid address for payouts, I consulted the fellow who ported idigdoge to Nyancoin, and he pointed that in order to make it to where an address that wasn't Doge would pass the payout someone would just change the "D" prefix under //Check The Address Structure listed in "/routes/front.js".  

But apparently that's changed recently and there's a separate page for address information under addresses.js. I made those same changes there but it still leaves me where it fails a valid address check for a different currency.  

Where should I be looking in order to make that change? Thanks for your input.

**Comment by 7THStage** [comment]
I should move this to configuration, but for now, here's the how-to.
1. In [line 38](https://github.com/7THStage/idigdoge/blob/master/addresses.js#L38), you'll need to change the first `D` to the appropriate character for your coin.
2. In [line 54](https://github.com/7THStage/idigdoge/blob/master/addresses.js#L54), you'll need to change `1e` to the appropriate hexadecimal number. This number (in decimal, it would be 30) is what is referred to as the "[public address prefix](https://en.bitcoin.it/wiki/List_of_address_prefixes)". It's visible in the Dogecoin source code [here](https://github.com/dogecoin/dogecoin/blob/6e5881a000e5b926b93143c70cd2fb00239d78f8/src/base58.h#L276) and I would guess it's in the same file for most other scrypt-based cryptos.

**Why I Changed It**

Dogecoin addresses are built to prevent typos. In most cases, switching one or two letters will not send your coins to a different address, but will instead come up with an error saying it's invalid. This is because the last portion of an address is a [checksum](https://en.wikipedia.org/wiki/Checksum).

Because I was only checking the first letter, length, and for invalid characters, sometimes IDD would accept an address that wasn't actually valid. This meant I would have to email the user to get the correct address. Eventually I'd had enough of that and decided to properly validate the address. It's a lot more complicated, but it means that when it accepts an address, it's gonna be valid.

**Comment by leadcoin** [comment]
That did it, thanks so much for following up.
