### ISSUE TITLE
All workers produce the same hashes?

### ISSUE THREAD

**Issue by Madumo** [7THStage/idigdoge#3]
Tell me if i'm wrong, but from what I understand of your code right now, when your coordinator receive a job, it ask to all workers to compute hashes with nonce = 0 and maxnonce = 250 (or 500 if pnacl).

So, it seem like every workers will compute the same 250 hashes.

**Comment by 7THStage** [comment]
I'll start with an explanation of how it should be working.

The `workSize` property of a worker defaults to 250 and 500. Because the workers are looping through data in a single thread, if they never stopped, they would never look for new work. So workSize limits the number of nonces they try before asking for updates.

However, if workers were taking too many breaks, that wouldn't be very efficient. If you look around line 24 of the `coordinator.js` file, you'll notice the workSize is changed after every group of work. The code tries target a check every five seconds. So if a worker is managing 1,000 hashes per second, it's workSize will be around 5,000.

Around line 157 is the `sendWork` function. It gets the nonce from the `workCache`, and passes it as the nonce to start on. It then increments the nonce stored by workCache and passes that as the maximum nonce. Because workCache applies to all workers, none of them should be doing the same work. The nonce is reset every new block.

If it's not working as described, please let me know, because that would really suck. :( But since my tests say it is, I'm gonna go ahead and close this for now.

**Comment by Madumo** [comment]
First of all, thanks a lot for explaining this to me so quickly. I didn't saw the workSize part at first.

But when does the workCache.nonce get updated to something other than 0 ? Even if the workSize change, it seem to me that all the workers produces the same hashes for a given workCache.

The coordinator get the computed block header from the server and store it in workCache.data. Then you append the nonce (always 0?) to it, and the computed maxNonce, which is the nonce + workSize (0 + worksize?).

Then, all workers will hash the same block header with the appended nonce which seem to be 0 to maxNonce.

Lets say we have two workers. The first have a work size of 5 and the other of 6. The first five hashes they will produce will be the same.

**Comment by 7THStage** [comment]
`workCache.nonce` gets updated precisely [here](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L164).

Here's a step by step. The blue stuff is all links to code, because GitHub is handy like that.
1. Work comes in, and is assigned to `workCache`, [setting `workCache.nonce` to zero](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L200).
2. A worker finishes work. [Their `workSize` is set to 500](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L24). [New work is triggered](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L27).
3. A work message is needed. The current nonce, which is zero at this time, [is saved](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L163) to the `start` variable. Then the nonce is increased by the workSize, which is 500 at this time, [and saved](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L164) to both the `end` variable and `workCache.nonce`, which will now both be equal to 500. Finally, the nonces are [combined with the rest of the header](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L165) and [sent](https://github.com/7THStage/idigdoge/blob/b2a61b2cc361f1bb3c1695c7150c3294819f3576/raw/coordinator.js#L167) along.
4. Another worker finishes it's work. It's `workSize` is set to 480.
5. Another work message is needed. It contains the current nonce, which is 500, and the new nonce, which will be 980. The nonces are combined with the rest of the header and sent along.

Let me know if that explains it better.

**Comment by Madumo** [comment]
Oh i see. Didn't realized the nonce got incremented at the same time because of the +=. I get it now, that make sens. Thanks a lot! :kissing_heart:
